### ISSUE TITLE
Brave is missing from Browsers list

### ISSUE THREAD

**Issue by erfanghorbanee** [AT3K/Ultimate-Privacy-Guide#1]
Hey there,

I find [Brave](https://brave.com/) browser a pretty straightforward solution for most people who do not have time to configure their browser to protect their privacy. Also, its ads-blocking feature is another thing that I personally am a fan of and think it is worth mentioning in the list.

Have a nice day.

**Comment by AT3K** [comment]
Hey there!

Thanks for sharing your thoughts on Brave! I totally get why many people find it appealing—it does have some nice features for privacy and ad-blocking.

That said, I have some reservations about it. While Brave markets itself as a privacy-focused browser, there have been discussions about how it handles user data and its ad model. Some folks feel that the way it integrates ads, even if they’re privacy-respecting, might go against the core idea of what privacy should be. Because of these concerns, I’ve chosen not to include it in the list.

I appreciate your perspective, though! It’s always great to hear different opinions on tools that aim to protect our privacy. If you have any other suggestions or insights, feel free to share!

---

**Note : This issue will be closed in 7 days after no response**

**Comment by erfanghorbanee** [comment]
I understand. Thanks for the response.
